# Generated by Django 4.1.5 on 2023-01-25 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Titulo/trabajo')),
                ('subtitle', models.CharField(max_length=150, verbose_name='Lugar')),
                ('description', models.TextField(verbose_name='Descripcion')),
                ('start_date', models.DateField(verbose_name='Inicio')),
                ('finish_date', models.DateField(verbose_name='Finalizacion')),
                ('public', models.BooleanField(verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Experiencia y estudio',
                'verbose_name_plural': 'Experiencia y estudio',
            },
        ),
    ]
