# Generated by Django 4.1.5 on 2023-01-26 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='education',
            field=models.BooleanField(default='False', verbose_name='Titulo_educativo'),
        ),
    ]
