# Generated by Django 4.1.5 on 2023-01-27 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_cv_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='Software_Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('public', models.BooleanField(verbose_name='Activo')),
            ],
        ),
    ]
