# Generated by Django 4.1.5 on 2023-02-01 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_software_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Albums',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Titulo')),
                ('type', models.CharField(max_length=150, verbose_name='Tipo')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('description', models.CharField(max_length=1500, verbose_name='Descrpción')),
                ('galery', models.ImageField(default='null', upload_to='', verbose_name='Galery')),
                ('front', models.ImageField(default='null', upload_to='', verbose_name='Portada')),
            ],
        ),
    ]
