# Generated by Django 4.1.5 on 2023-02-06 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_albums'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Albums',
            new_name='Album',
        ),
        migrations.RenameModel(
            old_name='Software_Skills',
            new_name='Software_Skill',
        ),
    ]
