# Generated by Django 4.1.5 on 2023-02-06 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_albums_album_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='galery',
        ),
        migrations.AlterField(
            model_name='album',
            name='front',
            field=models.ImageField(default='null', upload_to='media', verbose_name='Portada'),
        ),
        migrations.CreateModel(
            name='AlbumGalery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='null', upload_to='media', verbose_name='Galeria')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.album')),
            ],
        ),
    ]
