# Generated by Django 4.1.5 on 2023-02-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_albumgalery_image_alter_albumgalery_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='slug',
            field=models.CharField(default='null', max_length=50, unique=True, verbose_name='Url'),
        ),
    ]
