# Generated by Django 4.1.5 on 2023-02-10 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_album_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumgalery',
            name='image',
            field=models.ImageField(upload_to='media/gallery'),
        ),
    ]
