# Generated by Django 4.1.5 on 2023-02-10 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_albumgalery_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumgalery',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
