# Generated by Django 4.1.5 on 2023-02-10 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_albumgalery_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='front',
            field=models.ImageField(default='null', upload_to='media/', verbose_name='Portada'),
        ),
    ]
