# Generated by Django 4.1.5 on 2023-02-10 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_album_front'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre cliente')),
                ('mail', models.CharField(max_length=150, verbose_name='Mail')),
                ('project', models.CharField(max_length=150, verbose_name='Proyecto')),
                ('message', models.TextField(verbose_name='Mensaje')),
            ],
        ),
    ]
