# Generated by Django 4.1.5 on 2023-02-13 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Titulo')),
                ('subtitle', models.CharField(max_length=150, verbose_name='Subititulo')),
                ('content', models.TextField(max_length=9999, verbose_name='Descripcion')),
                ('img', models.ImageField(default='null', upload_to='media/', verbose_name='Imagen')),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_img', models.ImageField(default='null', upload_to='media/', verbose_name='Imagen Banner')),
                ('banner_title', models.CharField(max_length=50, verbose_name='Titulo banner')),
                ('banner_subtitle', models.CharField(max_length=50, verbose_name='Subtitulo banner')),
                ('presentation_text', models.TextField(max_length=500, verbose_name='Texto Presentacion')),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iframes', models.CharField(max_length=999, verbose_name='Iframe del video')),
                ('title', models.CharField(max_length=50, verbose_name='Titulo del video')),
                ('public', models.BooleanField(default=False, verbose_name='Publicado?')),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='read',
            field=models.BooleanField(default=False, verbose_name='Leido?'),
        ),
    ]
