# Generated by Django 4.1.5 on 2023-02-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_about_home_videos_contact_read'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name_plural': 'About'},
        ),
        migrations.AlterModelOptions(
            name='albumgalery',
            options={'verbose_name_plural': 'Album Gallery'},
        ),
        migrations.AlterModelOptions(
            name='home',
            options={'verbose_name_plural': 'Home'},
        ),
        migrations.AlterModelOptions(
            name='videos',
            options={'verbose_name': 'Video', 'verbose_name_plural': 'Videos'},
        ),
        migrations.AddField(
            model_name='about',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Publico?'),
        ),
        migrations.AddField(
            model_name='home',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Publico?'),
        ),
    ]
