# Generated by Django 4.1.5 on 2023-02-23 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_about_options_alter_albumgalery_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='gallery_title',
            field=models.CharField(default='null', max_length=50, verbose_name='Tito galeria home'),
        ),
    ]
