# Generated by Django 4.1.5 on 2023-02-23 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_home_gallery_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='gallery_title',
            field=models.CharField(max_length=50, verbose_name='Tito galeria home'),
        ),
    ]
